version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: identity-postgres
    environment:
      POSTGRES_DB: identity_service
      POSTGRES_USER: identity_user
      POSTGRES_PASSWORD: identity_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U identity_user -d identity_service"]
      interval: 5s
      timeout: 5s
      retries: 5

  identity-service:
    build: .
    container_name: identity-service
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://identity_user:identity_password@postgres:5432/identity_service?sslmode=disable
      JWT_SECRET: dev-jwt-secret-key-change-in-production
      ENVIRONMENT: development
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./.env:/root/.env
    restart: unless-stopped

volumes:
  postgres_data:
